set hive.abm.sampled.table = lineitem;

select
        n_name,
        sum(l_extendedprice * (1 - l_discount)) as revenue
from
        customer c
        join orders o on c.c_custkey = o.o_custkey
                and o.o_orderdate >= '1994-10-01' and o.o_orderdate < '1995-01-01'
        join nation n on c.c_nationkey = n.n_nationkey
        join lineitem l on l.l_orderkey = o.o_orderkey and l.l_returnflag = 'R'
group by
        n_name;



