set hive.abm.sampled.table = lineitem;

select
        sum(100.00 * case
               when p_type like 'PROMO%'
               then l_extendedprice*(1-l_discount)
               else 0.0
        end), sum(l_extendedprice * (1 - l_discount)) as promo_revenue
from
        lineitem l
        join part_cached p on l.l_partkey = p.p_partkey and l.l_shipdate >= '1996-12-01' and l.l_shipdate < '1997-01-01';



