set hive.abm.sampled.table = lineitem;

select
        o_orderdate,
        o_shippriority,
        sum(l_extendedprice*(1-l_discount)) as revenue
from
        customer c join orders o
                on (c.c_mktsegment = 'BUILDING' and c.c_custkey = o.o_custkey)
        join lineitem l on l.l_orderkey = o.o_orderkey 
where 
        o_orderdate < '1995-07-01'
        and o_orderdate > '1994-01-01'
        and l_shipdate > '1994-01-01'
group by
        o_orderdate, 
        o_shippriority;



